# Generated by Django 3.0.7 on 2020-07-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_id', models.CharField(max_length=200)),
                ('storage_hint', models.CharField(max_length=5000)),
                ('storage_picture', models.ImageField(default='', upload_to='storage_pictures/')),
                ('preview_image', models.ImageField(default='', upload_to='previews/')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('stl_count', models.IntegerField(default=0)),
                ('scrap_name_holder', models.CharField(max_length=200)),
                ('scrap_description_holder', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizerClass',
            fields=[
                ('scraptype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customizer.ScrapType')),
                ('camera_x', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('camera_y', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('camera_z', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('parameter_file', models.FileField(default='', upload_to='parameters/')),
            ],
            bases=('customizer.scraptype',),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customizer.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_description', models.CharField(max_length=200)),
                ('min_int', models.IntegerField(default=0)),
                ('max_int', models.IntegerField(default=200)),
                ('step_size', models.DecimalField(decimal_places=1, default=0.1, max_digits=2)),
                ('value', models.DecimalField(decimal_places=1, default=50.0, max_digits=7)),
                ('parent_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='customizer.CustomizerClass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
