# Generated by Django 3.0.7 on 2020-07-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0003_auto_20200713_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toggle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_description', models.CharField(max_length=200)),
                ('value', models.BooleanField(default=False)),
                ('parent_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toggles', to='customizer.CustomizerClass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
