# Generated by Django 3.0.7 on 2020-07-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0004_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='input_name',
            field=models.CharField(default='Height', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='toggle',
            name='input_name',
            field=models.CharField(default='Height', max_length=200, unique=True),
        ),
    ]
