# Generated by Django 3.0.7 on 2020-07-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0005_auto_20200713_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizerclass',
            name='script_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='scripts/'),
        ),
        migrations.AlterField(
            model_name='customizerclass',
            name='parameter_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='parameters/'),
        ),
    ]
