# Generated by Django 3.0.7 on 2020-07-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0006_auto_20200713_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='min_int',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
