# Generated by Django 3.0.7 on 2020-07-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0011_customizerclass_preview_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraptype',
            name='ui_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
