# Generated by Django 3.0.7 on 2020-07-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0014_auto_20200720_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraptype',
            old_name='scrap_image',
            new_name='scrap_image_holder',
        ),
    ]
