# Generated by Django 3.0.7 on 2020-07-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0015_auto_20200720_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapobject',
            name='stl_file',
            field=models.FileField(default=None, upload_to='STL/'),
        ),
        migrations.AlterField(
            model_name='scraptype',
            name='scrap_image_holder',
            field=models.FileField(blank=True, default='', null=True, upload_to='userimages/'),
        ),
    ]
