# Generated by Django 3.0.7 on 2020-08-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0019_auto_20200803_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapobject',
            name='number_stored',
            field=models.IntegerField(default=0),
        ),
    ]
